---                                                                                                                                              
- name: Ensure the mysql Repo file exists as per template                                                                                        
  template: src=/etc/ansible/roles/cloudstack-manager/templates/mysql.repo.j2 dest=/etc/yum.repos.d/mysql.repo                                   
- name: Ensure selinux python bindings are installed                                                                                             
  yum: name=libselinux-python state=present                                                                                                      
- name: Ensure selinux is in permissive mode
  command: setenforce permissive
- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive
- name: Ensure mysql server is installed                                                                                                         
  yum: name=mysql-server state=present                                                                                                           
- name: Ensure mysql python is installed                                                                                                         
  yum: name=MySQL-python state=present                                                                                                           
- name: Ensure cloudstack specfic my.cnf lines are present                                                                                       
  template: src=/etc/ansible/roles/cloudstack-manager/templates/my.cnf.j2 dest=/etc/my.cnf
- name: Ensure MySQL service is started                                                                                                          
  systemd: name=mysqld.service state=started                                                                                                             
- name: Ensure MySQL service is enabled at boot                                                                                                  
  systemd: name=mysqld.service enabled=yes                                                                                                               
- name: Ensure root password is set                                                                                                              
  mysql_user: user=root password={{mysql_cloud_password}} host=localhost                                                                            
#  ignore_errors: true                                                                                                                            
#- name: Ensure root has sufficient privileges                                                                                                    
#  mysql_user: login_user=root login_password=$mysql_root_password user=root host=% password=$mysql_root_password priv=*.*:GRANT,ALL state=present

