---
- name: Ensure secondary storage mount exists
  file: path={{ tmp_nfs_path }} state=directory
- name: Ensure  NFS storage is mounted
  mount: name={{ tmp_nfs_path }} src={{ sec_nfs_ip }}:{{ sec_nfs_path }} fstype=nfs state=mounted opts=nolock
- name: Copy systemvmtemplate to acs server
  copy: src=/cloudstack/packets/systemvm64template-4.6.0-kvm.qcow2.bz2 dest=/tmp/systemvm64template-4.6.0-kvm.qcow2.bz2
- name: Seed secondary storage
  command: /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m {{ tmp_nfs_path }} -f /tmp/systemvm64template-4.6.0-kvm.qcow2.bz2 -h kvm -F
